#!/usr/bin/env python3
"""
gen_rta_tables.py -- Spectrum analyser constant tables for DSPi.

Emits firmware/DSPi/rta_tables.h: complex and real-split twiddles (float and
Q15), the third-octave band edge tables for every (sample rate, order), the
log2 mantissa table, and the nominal band centres.  This script is the single
source of truth for the band layout: tools/rta_test imports band_bins(),
band_count(), band_edges() and band_centre_exact() from here rather than
reimplementing them.

Usage:
  python3 scripts/gen_rta_tables.py --out firmware/DSPi/rta_tables.h
"""

import argparse
import datetime
import math
import sys

# Must match RTA_ORDER_MIN / RTA_ORDER_MAX in rta_fft.h.
ORDER_MIN = 8
ORDER_MAX = 11
MAX_BANDS = 36

# Device sample rates the analyser supports.
RATES = (44100, 48000, 96000)

# The complex transform is half the real length.  The split pass pairs k with
# n/2-k and includes the self-paired k = n/4, hence the extra entry.
TW_N = 1 << (ORDER_MAX - 1)
SPLIT_N = (1 << ORDER_MAX) // 4 + 1

# IEC 61260 base-10 third-octave: fc = 1000 * 10^(i/10).  Band 0 is the 20 Hz
# band, so band b has i = b - 17 (10^-1.7 * 1000 = 19.953 Hz).
BAND_I0 = -17

# Nominal (displayed) centres, R10 preferred numbers.  Band 2 is 31.5 Hz and is
# carried as 32 because the caps field is whole Hz.
NOMINAL_HZ = (20, 25, 32, 40, 50, 63, 80, 100, 125, 160, 200, 250, 315, 400,
              500, 630, 800, 1000, 1250, 1600, 2000, 2500, 3150, 4000, 5000,
              6300, 8000, 10000, 12500, 16000, 20000, 25000, 31500, 40000)


def band_centre_exact(b):
    return 1000.0 * 10.0 ** ((b + BAND_I0) / 10.0)


def band_edges(b):
    fc = band_centre_exact(b)
    return fc * 10.0 ** -0.05, fc * 10.0 ** 0.05


def band_count(sample_rate_hz):
    """31 bands to 20 kHz below 50 kHz, 34 bands to 40 kHz above."""
    return 34 if sample_rate_hz > 50000 else 31


def band_bins(sample_rate_hz, order, n_bands):
    """First and last bin index of each band, as (lo, hi) pairs.

    A bin belongs to the band whose edges contain its centre frequency.  Bin 0
    (DC) never belongs to a band.  A band with no bin of its own is empty,
    encoded as lo > hi (1, 0), and reads the floor.
    """
    n = 1 << order
    n_bins = n // 2
    df = sample_rate_hz / float(n)
    out = []
    for b in range(n_bands):
        lo_e, hi_e = band_edges(b)
        klo = max(int(math.ceil(lo_e / df)), 1)
        khi = min(int(math.floor(hi_e / df)), n_bins - 1)
        if khi < klo:
            klo, khi = 1, 0
        out.append((klo, khi))
    return out


def fmt_rows(values, per_line, fmt, indent="    "):
    rows = []
    for i in range(0, len(values), per_line):
        rows.append(indent + " ".join(fmt(v) + "," for v in values[i:i + per_line]))
    return rows


def q15(x):
    v = int(round(x * 32768.0))
    return max(-32768, min(32767, v))


def twiddles(n_entries, denom):
    """(cos, -sin)(2 pi t / denom) for t in 0..n_entries-1, interleaved."""
    out = []
    for t in range(n_entries):
        a = 2.0 * math.pi * t / denom
        out.append(math.cos(a))
        out.append(-math.sin(a))
    return out


def band_table_literal(a, rate, order):
    nb = band_count(rate)
    pairs = band_bins(rate, order, nb)
    lo = [p[0] for p in pairs] + [1] * (MAX_BANDS - nb)
    hi = [p[1] for p in pairs] + [0] * (MAX_BANDS - nb)
    a("    {  /* %d Hz, order %d */" % (rate, order))
    a("        .sample_rate_hz = %uu, .order = %d, .n_bands = %d, .reserved = 0,"
      % (rate, order, nb))
    a("        .lo = {")
    for row in fmt_rows(lo, 12, lambda v: "%4d" % v, indent="            "):
        a(row)
    a("        },")
    a("        .hi = {")
    for row in fmt_rows(hi, 12, lambda v: "%4d" % v, indent="            "):
        a(row)
    a("        },")
    a("    },")


def emit(path):
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    o = []
    a = o.append

    a("/* DO NOT EDIT - generated by scripts/gen_rta_tables.py")
    a(" *")
    a(" * Generated:   %s" % stamp)
    a(" * Cmdline:     %s" % " ".join(sys.argv))
    a(" *")
    a(" * Orders:                 %d..%d (real points 1<<order)" % (ORDER_MIN, ORDER_MAX))
    a(" * Complex twiddles:       %d entries, W[t] = (cos, -sin)(2*pi*t/%d)" % (TW_N, TW_N))
    a(" *                         a block of length L strides the table by %d/L" % TW_N)
    a(" * Real-split twiddles:    %d entries at 2*pi*k/%d" % (SPLIT_N, 1 << ORDER_MAX))
    a(" * Sample rates:           %s Hz" % ", ".join(str(r) for r in RATES))
    a(" *")
    a(" * Bands:      IEC 61260 base-10 third-octave, fc = 1000 * 10^((b-17)/10),")
    a(" *             band 0 = 20 Hz nominal.  Edges at fc * 10^(-+0.05).  A bin")
    a(" *             belongs to the band whose edges contain its centre; bin 0")
    a(" *             (DC) belongs to none.  A band with no bin of its own is")
    a(" *             empty (lo > hi) and reads the floor.")
    a(" */")
    a("#pragma once")
    a("")
    a("#include <stdint.h>")
    a("#include \"rta_fft.h\"")
    a("")
    a("#define RTA_TW_N      %d   /* complex twiddles, largest transform */" % TW_N)
    a("#define RTA_SPLIT_N   %d   /* real-split twiddles */" % SPLIT_N)
    a("")

    tw = twiddles(TW_N, TW_N)
    sp = twiddles(SPLIT_N, 1 << ORDER_MAX)
    for floating in (True, False):
        a("#if RTA_SAMPLE_FLOAT" if floating else "#else /* Q15 */")
        ty = "float" if floating else "int16_t"
        fmt = (lambda v: "%16.9ef" % v) if floating else (lambda v: "%6d" % q15(v))
        a("static const %s rta_tw[2 * RTA_TW_N] = {" % ty)
        o.extend(fmt_rows(tw, 4, fmt))
        a("};")
        a("static const %s rta_split_tw[2 * RTA_SPLIT_N] = {" % ty)
        o.extend(fmt_rows(sp, 4, fmt))
        a("};")
    a("#endif")
    a("")

    lg = [int(round(65536.0 * math.log2(1.0 + i / 32.0))) for i in range(33)]
    a("/* log2(1 + i/32) in Q16, i = 0..32.  Interpolate between neighbours. */")
    a("static const uint32_t rta_log2_tab[33] = {")
    o.extend(fmt_rows(lg, 8, lambda v: "%6d" % v))
    a("};")
    a("")

    centres = list(NOMINAL_HZ) + [0] * (MAX_BANDS - len(NOMINAL_HZ))
    a("/* Nominal third-octave centres in Hz; 0 past the last defined band. */")
    a("static const uint16_t rta_band_centre_tab[RTA_MAX_BANDS] = {")
    o.extend(fmt_rows(centres, 12, lambda v: "%5d" % v))
    a("};")
    a("")

    n_orders = ORDER_MAX - ORDER_MIN + 1
    a("static const uint32_t rta_base_rate_hz[%d] = { %s };"
      % (len(RATES), ", ".join("%uu" % r for r in RATES)))
    a("static const RtaBandTable rta_tables_fast[%d][%d] = {" % (len(RATES), n_orders))
    for rate in RATES:
        a("  {")
        for order in range(ORDER_MIN, ORDER_MAX + 1):
            band_table_literal(a, rate, order)
        a("  },")
    a("};")
    a("")

    with open(path, "w") as f:
        f.write("\n".join(o))


def main():
    ap = argparse.ArgumentParser(description="DSPi spectrum analyser table generator")
    ap.add_argument("--out", default="firmware/DSPi/rta_tables.h")
    args = ap.parse_args()
    for r in RATES:
        for order in range(ORDER_MIN, ORDER_MAX + 1):
            pairs = band_bins(r, order, band_count(r))
            first = next((b for b, (lo, hi) in enumerate(pairs) if lo <= hi), None)
            sys.stderr.write("%6u Hz order %2d: %d bands, first resolved band %s (%g Hz)\n"
                             % (r, order, band_count(r), first, NOMINAL_HZ[first]))
    emit(args.out)
    sys.stderr.write("wrote %s\n" % args.out)


if __name__ == "__main__":
    main()
