#!/usr/bin/env python3
"""Generate the RTA bass decimator and band filters (requires scipy).

CIC3 /8 at 44.1/48k, /16 at 96k -> elliptic LP /8 -> 689.0625/750 Hz.
Constants are copied to RAM on restart: no flash access inside the audio tap.
"""
from pathlib import Path
import numpy as np
from scipy import signal

ROOT = Path(__file__).resolve().parents[1]

def design(rate):
    d = 16 if rate == 96000 else 8
    mid = rate / d
    fs = mid / 8
    # Fixed order, >= 80 dB rejection from the first alias into <=225 Hz.
    sos = signal.ellip(8, .1, 85, 225, fs=mid, output='sos')
    # Normalise every cascade prefix to <=1 peak gain, moving the inverse
    # gain into the next section. Equal per-section numerator gains would
    # amplify DC by 15x internally and clip fixed-point hot signals.
    for j in range(len(sos)-1):
        _, h = signal.sosfreqz(sos[:j+1], worN=65536, fs=mid)
        peak = max(abs(h))
        sos[j,:3] /= peak
        sos[j+1,:3] *= peak
    bands = []
    for b in range(14):
        fc = 1000 * 10 ** ((b - 20) / 10)
        lo, hi = fc * 10**-.05, fc * 10**.05
        # 6th-order Butterworth: a single biquad's 6 dB/octave skirts light
        # every bass band for one tone. Each section is b0*(1 - z^-2).
        _, poles, _ = signal.butter(3, [lo, hi], btype='bandpass', fs=fs, output='zpk')
        poles = sorted((p for p in poles if p.imag > 0), key=abs)
        assert len(poles) == 3
        band = np.array([[1, 0, -1, 1, -2*p.real, abs(p)**2] for p in poles])
        _, h = signal.sosfreqz(band, worN=65536, fs=fs)
        band[0,:3] /= max(abs(h))
        for j in range(2):
            _, h = signal.sosfreqz(band[:j+1], worN=65536, fs=fs)
            peak = max(abs(h))
            band[j,:3] /= peak
            band[j+1,:3] *= peak
        # Correct CIC, elliptic and bandpass gain at each centre, in power.
        cic = (np.sin(np.pi*fc*d/rate)/(d*np.sin(np.pi*fc/rate)))**3
        _, h = signal.sosfreqz(sos, worN=[fc], fs=mid)
        _, hb = signal.sosfreqz(band, worN=[fc], fs=fs)
        compensation = 1 / abs(cic*h[0]*hb[0])**2
        envelope = 1-np.exp(-fc/fs)  # tau = one centre-frequency period
        bands.append(([row[[0, 4, 5]] for row in band], envelope, compensation))
    return d, sos, bands

lines = ['/* Generated by scripts/gen_rta_bass.py; do not edit. */',
         'static const RtaBassCoeffs bass_tables[3] = {']
for rate in (44100,48000,96000):
    d,sos,bands=design(rate)
    lines += ['    { /* %d Hz */'%rate, '        .cic_shift = %d,'%(3*int(np.log2(d))),
              '        .decimation = %d,'%d, '        .lowpass = {']
    def value(x):
        assert abs(round(x*2**28)) < 2**31, x
        return '%.10ef'%x if FLOAT else str(int(round(x*2**28)))
    # Separate compile-time formats; all state remains 32 bits.
    for FLOAT in (True, False):
        lines.append('#if RTA_SAMPLE_FLOAT' if FLOAT else '#else')
        for row in sos:
            lines.append('            { '+', '.join(value(x) for x in [*row[:3],*row[4:]])+' },')
    lines += ['#endif','        },','        .band = {']
    for FLOAT in (True,False):
        lines.append('#if RTA_SAMPLE_FLOAT' if FLOAT else '#else')
        for sections, envelope, compensation in bands:
            lines.append('            { { '+', '.join('{ '+', '.join(value(x) for x in s)+' }'
                                                    for s in sections)+
                         ' }, %s, %.10ef },'%(value(envelope), compensation))
    lines += ['#endif','        },','    },']
lines += ['};','']
(ROOT/'firmware/DSPi/rta_bass_tables.h').write_text('\n'.join(lines))
